INSERT INTO `tsprachwerte` (`kSprachISO`, `kSprachsektion`, `cName`, `cWert`, `cStandard`, `bSystem`) VALUES
(1, 18, 'also_like', 'Weitere Beiträge', 'Noch nicht genug?', 0),
(1, 18, 'clone', 'Kopieren', 'Kopieren', 0),
(1, 18, 'featured_blog_entries', 'Beliebte Beiträge aus unserem Blog', 'Beliebte Beiträge aus unserem Blog', 0),
(1, 18, 'fees', 'Gebühren', 'Gebühren', 0),
(1, 18, 'handlingFee', 'Versandgebühren', 'Versandgebühren', 0),
(1, 18, 'lfa_notice', 'Diese Lieferadresse wird als Kopie gespeichert da sie bereits mit einer Bestellung verknüpft wurde.', 'Diese Lieferadresse wird als Kopie gespeichert da sie bereits mit einer Bestellung verknüpft wurde.', 0),
(1, 18, 'loadMoreReviews', 'Mehr Reviews laden', 'Mehr Reviews laden', 0),
(1, 18, 'noImage', 'Kein Bild verfügbar', 'Kein Bild verfügbar', 0),
(1, 18, 'note', 'Hinweis', 'Hinweis', 0),
(1, 18, 'quick_view', 'Quick view', 'Quick view', 0),
(1, 18, 'rating_helpful', '%s von %s Kunden<br>fanden diese Bewertung hilfreich', '%s unserer Kunden<br>fanden diese Bewertung hilfreich', 0),
(1, 18, 'ratings_helpful', '%s unserer Kunden<br>fanden diese Bewertungen hilfreich', '%s Kunden<br>fanden die Bewertungen hilfreich', 0),
(1, 18, 'reviewDefaultText', 'Kundenzufriedenheit ist uns extrem wichtig und wir freuen uns, wenn Sie uns ihre Eindrücke und Feedback mitteilen könnten. Es wäre toll, wenn Sie sich kurz die Zeit nehmen, eine Bewertung zu schreiben. Denn dann helfen Sie auch anderen Kunden bei der Auswahl.<br>\r\nUm Ihre Bewertung zu schreiben und abzuschicken, genügt ein Klick!', 'Hier könnte Ihre Bewertung stehen', 0),
(1, 18, 'reviewDefaultTitel', 'Hier könnte Ihre Bewertung stehen', 'Hier könnte Ihre Bewertung stehen', 0),
(1, 18, 'share', 'Teilen', 'Teilen', 0),
(1, 18, 'show', 'Öffnen', 'Öffnen', 0),
(1, 18, 'show_product', 'Produkt öffnen', 'Produkt öffnen', 0),
(1, 18, 'social_share', 'Beitrag teilen', 'Beitrag teilen', 0),
(1, 18, 'summary', 'Bestätigung', 'Bestätigung', 0),
(2, 18, 'also_like', 'You may also like', 'You may also like', 0),
(2, 18, 'clone', 'Copy', 'Copy', 0),
(2, 18, 'featured_blog_entries', 'Popular posts from our blog', 'Popular posts from our blog', 0),
(2, 18, 'fees', 'Fees', 'Fees', 0),
(2, 18, 'handlingFee', 'Handling fee', 'Handling fee', 0),
(2, 18, 'lfa_notice', 'This delivery address is saved as a copy because it has already been linked to an order.', 'This delivery address is saved as a copy because it has already been linked to an order.', 0),
(2, 18, 'loadMoreReviews', 'Load more reviews', 'Load more reviews', 0),
(2, 18, 'noImage', 'No image available', 'No image available', 0),
(2, 18, 'note', 'Note', 'Note', 0),
(2, 18, 'quick_view', 'Quick view', 'Quick view', 0),
(2, 18, 'rating_helpful', '%s out of %s customers<br> found the review helpful', '', 0),
(2, 18, 'ratings_helpful', '%s out of our customers<br> found the reviews helpful', '%s customers<br> found the reviews helpful', 0),
(2, 18, 'reviewDefaultText', 'Customer satisfaction is extremely important to us and we would appreciate it if you could give us your impressions and feedback. It would be great if you would take a moment to write a review. Because then you will also help other customers with their selection.<br>\r\nOne click is enough to write and send your review!', 'This could be your review', 0),
(2, 18, 'reviewDefaultTitel', 'This could be your review', 'This could be your review', 0),
(2, 18, 'share', 'Share', 'Share', 0),
(2, 18, 'show', 'Show', 'Show', 0),
(2, 18, 'show_product', 'See product', 'See product', 0),
(2, 18, 'social_share', 'Share post', 'Share post', 0),
(2, 18, 'summary', 'Review', 'Review', 0);
